calendareshop/shopping/urls.py
from django.conf.urls import include, patterns, url

from views import shop


urlpatterns = patterns('',
    url(r'', include(shop.urls)),
    url(r'^products/$', 'shopping.views.product_list', name='plata_product_list'),
    url(r'^products/(?P<object_id>\d+)/$', 'shopping.views.product_detail', name='plata_product_detail'),

    url(r'^email_test/(?P<order_id>\d+)/(?P<template>[\w_-]+)/$', 'shopping.views.email_test', name='email_test'),

    url(r'^reporting/', include('plata.reporting.urls')),
    url(r'^order-report/', 'shopping.views.order_report', name='order-report'),
    url(r'^gdpr_consent/', 'shopping.views.gdpr_consent', name='gdpr-consent'),
)

calendareshop/voting/urls.py
from django.conf.urls import include, patterns, url


urlpatterns = [
    url(r'^vote/(?P<email>[\w@._]+)/(?P<hash>\w+)/$', 'voting.views.vote', name='voting_vote'),
    url(r'results/', 'voting.views.results', name='voting_results'),
]

calendareshop/shopping/models.py
# -*- coding: utf-8 -*-
from collections import OrderedDict
from decimal import Decimal
import logging
import hashlib

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from plata.product.models import ProductBase
from plata.shop.models import PriceBase, Order
from calendareshop.models import Project
from .notifications import SendConfirmedHandler, SendPaidHandler

from plata.shop import signals as shop_signals

logger = logging.getLogger(__name__)


def email_hash(email):
    """
    Hash email with saltto generate authorized links for use in emails
    """
    h = hashlib.sha256()
    h.update(email)
    h.update(settings.SECRET_KEY)
    # salt it!
    h.update("Twillight sparkle $#% da best p0ny2423")
    return h.hexdigest()


#shop_signals.contact_created.connect(
#    notifications.ContactCreatedHandler(always_bcc=[]),
#    weak=False)
shop_signals.order_confirmed.connect(
    SendConfirmedHandler(always_bcc=settings.ALWAYS_BCC),
    weak=False)
shop_signals.order_paid.connect(
    SendPaidHandler(always_bcc=settings.ALWAYS_BCC),
    weak=False)
#shop_signals.order_paid.connect(
#    notifications.SendPackingSlipHandler(
#        always_to=[],
#        always_bcc=[settings.DEFAULT_FROM_EMAIL]),
#    weak=False)


class CustomOrder(Order):
    #: Order object is a cart.
    CART = 10
    #: Checkout process has started.
    CHECKOUT = 20
    #: Order has been confirmed, but it not (completely) paid for yet.
    CONFIRMED = 30
    #: Order has been completely paid for.
    PAID = 40
    #: Order has been completed. Plata itself never sets this state,
    #: it is only meant for use by the shop owners.
    COMPLETED = 50

    shipping_type = models.ForeignKey('Shipping', related_name='orders', null=True, blank=True)
    payment_type = models.ForeignKey('Payment', related_name='orders', null=True, blank=True)

    shipping_price = models.PositiveIntegerField(_('Shipping price'), default=0)
    payment_price = models.PositiveIntegerField(_('Payment price'), default=0)

    payment_cost = models.DecimalField(
        _('payment cost'),
        max_digits=18, decimal_places=10, blank=True, null=True)
    payment_tax = models.DecimalField(
        _('payment tax'),
        max_digits=18, decimal_places=10, default=Decimal('0.00'))

    personal_information_consent = models.BooleanField(default=False)
    personal_information_consent_date = models.DateTimeField(blank=True, null=True)
    personal_information_consent_years = models.PositiveIntegerField(default=settings.PERSONAL_INFORMATION_CONSENT_YEARS)

    class Meta:
        verbose_name = _('order')
        verbose_name_plural = _('orders')

    def save(self, *args, **kwargs):
        # skip Order.save() method, we don't want to have different order ID after pay
        super(Order, self).save(*args, **kwargs)
        # if _order_id is set for some reason, make it unset again
        if self._order_id:
            self._order_id = ''
            super(Order, self).save(*args, **kwargs)
    save.alters_data = True

    @property
    def order_id(self):
        return _(u'No. ') + unicode(self.id)

    @property
    def total_quantity(self):
        return sum([i.quantity for i in self.items.all()])

    @property
    def total_shipping_price(self):
        if self.shipping_type:
            return self.shipping_type.get_shipping_price(self.total_quantity, self.currency, country_code=self.billing_country)
        return 0

    @property
    def total_payment_price(self):
        if self.payment_type:
            return self.payment_type.get_payment_price(self)
        return 0

    @property
    def payment(self):
        """
        Returns the payment cost, with or without tax depending on this
        order's ``price_includes_tax`` field.
        """
        if self.price_includes_tax:
            if self.payment_cost is None:
                return None

            return (
                self.payment_cost +
                self.payment_tax)
        else:
            logger.error(
                'Payment calculation with'
                ' PLATA_PRICE_INCLUDES_TAX=False is not implemented yet')
            raise NotImplementedError

    @property
    def handling(self):
        return self.shipping + self.payment


class ProductManager(models.Manager):

    def active(self):
        return self.get_queryset().filter(is_active=True)


class Product(ProductBase):
    is_active = models.BooleanField(_('is active'), default=True)
    is_available = models.BooleanField(_('is available'), default=True)
    is_main = models.BooleanField(_('is main product'), default=True)
    name = models.CharField(_('name'), max_length=100)
    slug = models.SlugField(_('slug'), unique=True)
    ordering = models.PositiveIntegerField(_('ordering'), default=0)
    description = models.TextField(_('description'), blank=True)
    image = models.ImageField(upload_to="products/")
    items_in_stock = models.IntegerField(default=0)

    projects = models.ManyToManyField(Project, related_name="products")

    objects = ProductManager()

    class Meta:
        ordering = ['ordering', 'name']
        verbose_name = _('product')
        verbose_name_plural = _('products')

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('plata_product_detail', (), {'object_id': self.pk})


class ProductPrice(PriceBase):
    product = models.ForeignKey(Product, verbose_name=_('product'), related_name='prices')

    class Meta:
        get_latest_by = 'id'
        ordering = ['-id']
        verbose_name = _('price')
        verbose_name_plural = _('prices')


class PaymentManager(models.Manager):

    def active(self):
        return self.get_queryset().filter(is_active=True)


class Payment(models.Model):
    module = models.CharField(_('module code'), choices=settings.PLATA_PAYMENT_MODULE_NAMES.items(), max_length=10)
    name = models.CharField(_('name'), max_length=50)
    is_active = models.BooleanField(default=True)

    objects = PaymentManager()

    class Meta:
        verbose_name = _('payment')
        verbose_name_plural = _('payments')

    def __unicode__(self):
        return self.name

    def get_payment_price(self, order):
        if self.module == 'paypal':
            # 3% + fixed ammount based on currency
            price = (float(order.subtotal) * 0.03) + settings.PAYPAL_TRANSACTION_PRICES[order.currency]
            logger.info('Calculating PayPal transaction price as 3%% of %s + %s (%s) = %s',
                        order.subtotal, settings.PAYPAL_TRANSACTION_PRICES[order.currency], order.currency, price)
            return price
        return 0.0


class ShippingManager(models.Manager):

    def active(self):
        return self.get_queryset().filter(is_active=True)


class Shipping(models.Model):
    name = models.CharField(_('name'), max_length=50)
    code = models.CharField(_('code'), max_length=10)
    is_active = models.BooleanField(default=True)

    payments = models.ManyToManyField(Payment, related_name='shippings', through='ShippingPayment')

    objects = ShippingManager()

    class Meta:
        verbose_name = _('shipping')
        verbose_name_plural = _('shippings')

    def __unicode__(self):
        return self.name

    def get_shipping_price(self, quantity, currency, country_code=None, region=None):
        filters = dict(
            shipping=self,
            quantity_min__lte=quantity,
            quantity_max__gte=quantity,
        )
        if country_code:
            filters['region__countries__code'] = country_code
        elif region:
            filters['region'] = region
        ship_reg = ShippingRegion.objects.filter(**filters).first()
        if ship_reg:
            try:
                return int(ship_reg.shipping_region_prices.get(currency=currency).unit_price)
            except ShippingRegionPrice.DoesNotExist:
                raise LookupError("Price for country %s, shipping %s, quantity %s and currency %s is missing, add it please!" % (country_code, self, quantity, currency))
        return 0


class Region(models.Model):
    code = models.CharField(_('code'), max_length=2, primary_key=True)
    name = models.CharField(_('name'), max_length=50)

    class Meta:
        verbose_name = _('region')
        verbose_name_plural = _('regions')

    def __unicode__(self):
        return self.name

    def get_region_by_country_code(self, code):
        return Region.objects.filter(countries__code=code).first()


class Country(models.Model):
    code = models.CharField(_('code'), max_length=2, primary_key=True)
    name = models.CharField(_('name'), max_length=255, unique=True)
    region = models.ForeignKey(Region, related_name='countries', blank=True, null=True)

    class Meta:
        ordering = ('name', )
        verbose_name = _('country')
        verbose_name_plural = _('countries')

    def __unicode__(self):
        return u"%s (%s)" % (self.name, self.code)

    @staticmethod
    def choices():
        uncategorized = []
        categorized = OrderedDict()
        for region in Region.objects.prefetch_related('countries'):
            if region.code == 'CZ':
                country = region.countries.first()
                uncategorized.append((country.pk, country.name))
            elif region.code == 'SK':
                country = region.countries.first()
                uncategorized.append((country.pk, country.name))
            else:
                categorized[region.name] = tuple(region.countries.values_list('pk', 'name'))
        return uncategorized + categorized.items()


class ShippingRegion(models.Model):
    quantity_min = models.PositiveIntegerField(_('min quantity'))
    quantity_max = models.PositiveIntegerField(_('max quantity'))

    shipping = models.ForeignKey(Shipping, related_name='shipregions')
    region = models.ForeignKey(Region, related_name='shipregions')

calendareshop/shopping/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from plata.contact.forms import CheckoutForm
from plata.shop import signals

from django_countries.fields import LazyTypedChoiceField

from .models import CustomOrder, Shipping, Payment, Region, Country


class CustomCheckoutForm(CheckoutForm):
    class Meta:
        fields = ['email', 'shipping_same_as_billing', 'personal_information_consent']
        fields.extend('billing_%s' % f for f in CustomOrder.ADDRESS_FIELDS)
        fields.extend('shipping_%s' % f for f in CustomOrder.ADDRESS_FIELDS)
        model = CustomOrder

    billing_address = forms.CharField(label=_('address'), required=True)
    shipping_address = forms.CharField(label=_('address'), required=False)
    # override it so it will be required
    billing_country = LazyTypedChoiceField(label=_('Country'), choices=Country.choices(), required=True)
    shipping_country = LazyTypedChoiceField(label=_('Country'), choices=Country.choices(), required=False)
    personal_information_consent = forms.BooleanField(label=_('<a href="/personal-information-protection/" target="_blank">I agree to provide my personal information</a>.'), required=True)

    def clean(self):
        data = super(CustomCheckoutForm, self).clean()

        if not data.get('shipping_same_as_billing'):
            for f in self.REQUIRED_ADDRESS_FIELDS:
                field = 'shipping_%s' % f
                if not data.get(field):
                    self._errors[field] = self.error_class([
                        _('This field is required.')])

        return data


class ShippingPaymentForm(forms.Form):
    class Meta:
        fields = ['notes', 'shipping_type',
                  'payment_type', 'terms_and_conditions']

    notes = forms.CharField(label=_('notes'), required=False, widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}))
    terms_and_conditions = forms.BooleanField(
        label=_('I accept the <a href="/terms-conditions/" target="_blank">terms and conditions</a>.'),
        required=True
    )

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        self.shop = kwargs.pop('shop')
        self.order = kwargs.pop('order')
        super(ShippingPaymentForm, self).__init__(*args, **kwargs)
        self.payment_modules = self.shop.get_payment_modules(self.request)

        # TODO sanitize possible exceptions
        # set shipping types based on region
        total_quantity = self.order.total_quantity
        region = Region.objects.filter(countries__code=self.order.billing_country.code)
        shippings = Shipping.objects.active().filter(shipregions__region=region, shipregions__quantity_min__lte=total_quantity, shipregions__quantity_max__gte=total_quantity)
        self.fields['shipping_type'] = forms.ChoiceField(
            choices=shippings.values_list('id', 'name'),
            widget=forms.RadioSelect(attrs={'settings': settings}),
            required=True
        )
        payments = set()
        for shipping in shippings:
            payments.update(shipping.payments.active())
        self.fields['payment_type'] = forms.ChoiceField(
            choices=[(payment.id, payment.name) for payment in payments],
            widget=forms.RadioSelect(attrs={'settings': settings}),
            required=True
        )

    def clean(self):
        data = super(ShippingPaymentForm, self).clean()
        self.order.validate(self.order.VALIDATE_ALL)

        shipping_type_id = data.get('shipping_type', None)
        data['shipping_type'] = Shipping.objects.filter(pk=shipping_type_id).first()

        payment_type_id = data.get('payment_type', None)
        data['payment_type'] = Payment.objects.active().filter(pk=payment_type_id).first()

        return data

    def save(self):
        if 'shipping_type' in self.cleaned_data:
            self.order.shipping_type = self.cleaned_data['shipping_type']
        if 'payment_type' in self.cleaned_data:
            self.order.payment_type = self.cleaned_data['payment_type']
        if 'notes' in self.cleaned_data:
            self.order.notes = self.cleaned_data['notes']
        self.order.save()


class CustomConfirmationForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.order = kwargs.pop('order')
        self.request = kwargs.pop('request')
        self.shop = kwargs.pop('shop')
        self.payment_modules = self.shop.get_payment_modules(self.request)
        super(CustomConfirmationForm, self).__init__(*args, **kwargs)

    def clean(self):
        data = super(CustomConfirmationForm, self).clean()
        self.order.validate(self.order.VALIDATE_ALL)
        return data

    def process_confirmation(self):
        """
        Process the successful order submission
        """
        self.order.update_status(self.order.CONFIRMED, 'Confirmation given')
        signals.order_confirmed.send(
            sender=self.shop,
            order=self.order,
            request=self.request)

        module = dict(
            (m.key, m) for m in self.payment_modules
        )[self.order.payment_type.module]

        return module.process_order_confirmed(self.request, self.order)

calendareshop/shopping/templates/plata/_address.html
<div class="panel panel-default">
    <div class="panel-body">
        {% if address.company %}{{ address.company }}<br />{% endif %}
        {{ address.first_name }} {{ address.last_name }}<br />
        {{ address.address|linebreaksbr }}<br />
        {{ address.zip_code }} {{ address.city }}<br />
        {{ address.country }}
    </div>
</div>

calendareshop/shopping/templates/plata/_order_overview.html
{% load i18n bootstrap3 shopping_tags %}
{% with order.addresses as addresses %}
<h2>{% trans "Billing address" %}</h2>
{% with addresses.billing as address %}{% include "plata/_address.html" %}{% endwith %}

<h2>{% trans "Shipping address" %}</h2>
{% with addresses.shipping as address %}{% include "plata/_address.html" %}{% endwith %}
{% endwith %}

<h2>{%trans "Notes"%}</h2>
<div class="panel panel-default">
    <div class="panel-body">
    {{order.notes}}
    </div>
</div>

<h2>{% trans "Order items" %}</h2>
<table class="table table-striped">
{% for item in order.items.all %}
<tr>
    <td>{{ item.product }}</td>
    <td>{{ item.quantity }} × {% format_price item.unit_price item.currency %}</td>
    <td>{% format_price item.discounted_subtotal item.currency %}</td>
</tr>
{% endfor %}
<tr>
    <td>{%trans "Shipping method"%}</td>
    <td></td>
    <td>{{order.shipping_type}}</td>
</tr>
<tr>
    <td>{%trans "Payment method"%}</td>
    <td></td>
    <td>{{order.payment_type}}</td>
</tr>
</table>


{% with order.applied_discounts.all as discounts %}
  {% if discounts %}
    <h2>{% trans "Discounts" %}</h2>
      {% for discount in discounts %}
        <tr>
          <td>{{ discount.name }}</td>
          <td>{{ discount.code }}</td>
        </tr>
      {% endfor %}
    </table>
  {% endif %}

  <h2>{% trans "Total" %}</h2>
  <table class="table table-striped">
    <tr>
      <th>{% trans "subtotal"|capfirst %}</th>
      <td>{% format_price order.subtotal order.currency %}</td>
    </tr>
    {% if discounts %}
      <tr>
        <th>{% trans "discount"|capfirst %}</th>
        <td>{% format_price order.discount order.currency %}</td>
      </tr>
    {% endif %}
    <tr>
      <th>{% trans "shipping"|capfirst %}</th>
      <td>{% format_price order.shipping order.currency %}</td>
    </tr>
    <tr>
      <th>{% trans "payment"|capfirst %}</th>
      <td>{% format_price order.payment order.currency %}</td>
    </tr>
    <tr>
      <th>{% trans "tax from total amount"|capfirst %}</th>
      <td>{% format_price order.tax order.currency %}</td>
    </tr>
    <tr>
      <th>{% trans "total"|capfirst %}</th>
      <td>{% format_price order.total order.currency %}</td>
    </tr>
  </table>
{% endwith %}

calendareshop/shopping/templates/plata/shop_cart.html
{% extends base_template|default:"base.html" %}

{% load i18n bootstrap3 plata_tags shopping_tags %}

{% block title %}{% trans "Cart" %} - {{ block.super }}{% endblock %}

{% block content %}
{% if empty %}
<h1>{% trans "Cart is empty!" %}</h1>
{% else %}
<h1>{% trans "Cart" %}</h1>

<form method="post" action=".">{% csrf_token %}{{ orderitemformset.management_form }}
    {% form_errors orderitemformset %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>{% trans "product"|capfirst %}</th>
                <th>{% trans "quantity"|capfirst %}</th>
                <!--<th>{% trans "unit price"|capfirst %}</th>-->
                <th>{% trans "price"|capfirst %}</th>
                <th>{% trans "Delete" %}</th>
            </tr>
        </thead>
    {% for orderitemform in orderitemformset.forms %}
        <tr>
            <td>{{ orderitemform.instance.product }}</td>
            <td>
                {{ orderitemform.id }}
                <span class="quantity-counter">
                    <img src="{{STATIC_URL}}img/button_minus.gif" alt="-" class="btn-quantity" data-op="sub"/>
                    {% form_item_plain orderitemform.quantity additional_classes='test' %}
                    <img src="{{STATIC_URL}}img/button_plus.gif" alt="+" class="btn-quantity" data-op="add" />
                </span>
            </td>
            <!--<td>{{ orderitemform.instance.unit_price|floatformat:2}}</td>-->
            <td>{% format_price orderitemform.instance.discounted_subtotal order.currency%}</td>
            <td>{% form_item_plain orderitemform.DELETE %}</td>
        </tr>
    {% endfor %}
    </table>
    <div class="text-right buttons">
        {%buttons%}
        <input type="submit" name="save" value="{% trans "Recount" %}" class="btn" />
        <input type="submit" name="checkout" value="{% trans "Continue" %}" class="btn" />
        {%endbuttons%}
    </div>
</form>
{% endif %}
{% endblock %}

calendareshop/shopping/templates/plata/shop_checkout.html
{% extends base_template|default:"base.html" %}

{% load i18n plata_tags bootstrap3 shopping_tags%}

{% block title %}{% trans "Checkout" %} - {{ block.super }}{% endblock %}

{% block content %}

<div class="row">
    <div class="shop-header">
        <h2 class="go-back"><a href="{%url "plata_shop_cart"%}">{%trans "Cart"%}</a><h2>
        <h1>{% trans "Checkout" %}</h1>
        <h2>{%trans "shipping &amp; payment"|capfirst%}</h2>
    </div>

    {% comment %}
    {% if loginform %}
        <form method="post" action=".">{% csrf_token %}
        <input type="hidden" name="_login" value="1" />
        {% form_errors loginform %}

        <table class="table table-striped">
            {{ loginform }}
            <tr>
            <td></td>
            <td><button type="submit">{% trans "Submit" %}</button></td>
            </tr>
        </table>
        </form>
        {% if orderform.create_account %}
            {% form_item orderform.create_account %}
        {% endif %}

    {% endif %}
    {% endcomment %}
    
    <div class="col-md-8 col-md-offset-2">

        <form method="post" action="." class="form-horizontal">
            {% csrf_token %}
            <input type="hidden" name="_checkout" value="1" />

            <h2>{% trans "Billing address" %}</h2>

            {% bootstrap_form_errors orderform %}

            <div class="row form-block">
                <!--<div class="col-md-6">
                    {% bootstrap_field orderform.billing_company %}
                </div>-->
                <div class="col-md-6">
                    {% bootstrap_field orderform.billing_first_name%}
                </div>
                <div class="col-md-6">
                    {% bootstrap_field orderform.billing_last_name%}
                </div>
                <div class="col-md-6">
                    {% bootstrap_field orderform.billing_address %}
                </div>
                <div class="col-md-6">
                    {% bootstrap_field orderform.billing_city %}
                </div>
                <div class="col-md-6">
                    {% bootstrap_field orderform.billing_zip_code %}
                </div>
                <div class="col-md-6">
                    {% bootstrap_field orderform.billing_country %}
                </div>
                <div class="col-md-6">
                    {% bootstrap_field orderform.email%}
                </div>

            </div>
            
            
            <h2>{% trans "Shipping address" %}</h2>
            
            <div class="row form-block">
                {% bootstrap_field orderform.shipping_same_as_billing layout='horizontal' %}

                <div id="shipping-info" style="display: none;">
                    <!--<div class="col-md-6">
                        {% bootstrap_field orderform.shipping_company %}
                    </div>-->
                    <div class="col-md-6">
                        {% bootstrap_field orderform.shipping_first_name%}
                    </div>
                    <div class="col-md-6">
                        {% bootstrap_field orderform.shipping_last_name%}
                    </div>
                    <div class="col-md-6">
                        {% bootstrap_field orderform.shipping_address %}
                    </div>
                    <div class="col-md-6">
                        {% bootstrap_field orderform.shipping_city %}
                    </div>
                    <div class="col-md-6">
                        {% bootstrap_field orderform.shipping_zip_code %}
                    </div>
                    <div class="col-md-6">
                        {% bootstrap_field orderform.shipping_country %}
                    </div>
                </div>
            </div>
            <div class="row form-block">
                {% bootstrap_field orderform.personal_information_consent show_label=False %}
            </div>

            <div class="text-right">
            {%buttons%}
                <button type="submit" class="btn btn-success">{% trans "Continue" %}</button>
            {%endbuttons%}
            </div>
        </form>
    </div>
</div>
{% endblock %}

calendareshop/shopping/templates/plata/shop_shipping_payment.html
{% extends base_template|default:"base.html" %}

{% load i18n plata_tags bootstrap3 shopping_tags%}

{% block title %}{% trans "Shipping &amp; Payment" %} - {{ block.super }}{% endblock %}

{%block additional_css%}
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}tooltipster/css/tooltipster.bundle.min.css" />
{%endblock%}

{%block additional_js%}
<script type="text/javascript" src="{{STATIC_URL}}tooltipster/js/tooltipster.bundle.min.js"></script>
<script type="application/javascript">
	// tooltip
	//$(document).ready(function() {
	//	$('.tooltip').tooltipster();
	//});
	$(function () {
  		$('[data-toggle="tooltip"]').tooltip()
	})


	var shipping_payment = {{shipping_payment_json|safe}};
    var all_payment_ids = {{all_payment_ids_json|safe}};
    var selected_shipping = {{selected_shipping}};

    // check upon load
    if (selected_shipping) {
        check_shipping_payment($('#id_shipping_type input[value=' + selected_shipping + ']'));
    }
    //check on shipping change
    $('#id_shipping_type input[name=shipping_type]').change(function() {
        check_shipping_payment(this);
    });

    function check_shipping_payment(elem) {
        var val = $(elem).val();
        console.log("Shipping type changed to " + val);
        var used_payments = [];
        for (var shipping in shipping_payment) {
            if (shipping == val) {
                console.log(shipping_payment[shipping]['payment']);
                for (var i = 0; i < shipping_payment[shipping]['payment'].length; i++) {
                    var payment = shipping_payment[shipping]['payment'][i];
                    used_payments.push(payment);

                    $('#payment_' + payment).show();
                }
            }
        }
        var diff = $(all_payment_ids).not(used_payments).get();
        console.log("Hide there sayment ids: " + diff);
        $.each(diff, function(index, val) {
            console.log("Hiding payment " + val);
            $('#payment_' + val + ' input').prop('checked', false);
            $('#payment_' + val).hide();
        });
    }
</script>
{%endblock%}

{% block content %}
<div class="row">
    <div class="shop-header">
        <h2 class="go-back"><a href="{%url "plata_shop_checkout"%}">{%trans "Cart"%}</a><h2>
        <h1>{% trans "Shipping &amp; Payment" %}</h1>
        <h2>{%trans "confirmation"|capfirst%}</h2>
    </div>

    <div class="col-md-8 col-md-offset-2">

        <form method="post" action="." class="form-horizontal">
            {% csrf_token %}
            <input type="hidden" name="_checkout" value="1" />

            <h2>{%trans "Shipping method"%}</h2>

            <div class="form-group {%if form.shipping_type.errors%}has-error{%endif%}">
                <div id="{{form.shipping_type.id_for_label|slice:":-2"}}">
                {%for item in form.shipping_type.field.choices%}
                    <div class="radio">
                        <label for="{{form.shipping_type.html_name}}_{{item.0}}">
                            <input type="radio" name="{{form.shipping_type.html_name}}" id="{{form.shipping_type.html_name}}_{{item.0}}" value="{{item.0}}"
                                {%if selected_shipping == item.0%}checked="checked"{%endif%} />
                            {%trans item.1%}
                            <span>
                                {%for key, values in shipping_payment.items%}
                                    {%if key == item.0%}
                                        {%if values.price > 0%}
                                        ( + {% format_price values.price order.currency %} )
                                        {%else%}
                                            <span class="fa fa-info-circle" data-toggle="tooltip" data-placement="top"
												title="{%blocktrans%}Delivery only after personal confirmation in Prague Vrsovice,
you will receive more information about precise location and pick-up times after finishing the order process.{%endblocktrans%}">
											</span>
                                        {%endif%}
                                    {%endif%}
                                {%endfor%}
                            </span>
                        </label>
                    </div>
                {%endfor%}
                </div>
                {% for error in form.shipping_type.errors%}
                    <span class="help-block">{{error|escape}}</span>
                {%endfor%}
            </div>


            <h2>{%trans "Payment method"%}</h2>

            <div class="form-group {%if form.payment_type.errors%}has-error{%endif%}">
                <div id="{{form.payment_type.id_for_label|slice:":-2"}}">
                {%for item in form.payment_type.field.choices%}
                    <div class="radio" id="payment_{{item.0}}" {%if item.0 == 'cod'%}style="display: none;"{%endif%}>
                        <label for="{{form.payment_type.html_name}}_{{item.0}}">
                            <input type="radio" name="{{form.payment_type.html_name}}" id="{{form.payment_type.html_name}}_{{item.0}}"value="{{item.0}}"
                                {%if selected_payment == item.0%}checked="checked"{%endif%} />
                            {%trans item.1%}
                            <span>
                                {%for key, data in payment_payment.items%}
                                    {%if key == item.0%}
                                        {%if data.0 and data.0 > 0%}
                                        ( + {% format_price data.0 order.currency %} )
                                        {%endif%}
                                    {%endif%}
                                {%endfor%}
                            </span>
                        </label>
                    </div>
                {%endfor%}
                </div>
                {% for error in form.payment_type.errors%}
                    <span class="help-block">{{error|escape}}</span>
                {%endfor%}
            </div>

            <h2>{% trans "Notes" %}</h2>
            {% bootstrap_field form.notes show_label=False %}

            {% bootstrap_field form.terms_and_conditions show_label=False %}

            <div class="text-right">
            {%buttons%}
                <button type="submit" class="btn btn-success">{% trans "Continue" %}</button>
            {%endbuttons%}
            </div>
        </form>
    </div>
</div>
{% endblock %}